In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [14]:
df=pd.read_csv(r"C:\Users\abdul\Documents\BIA\ML\Dataset\train_LZdllcl.csv")
df.head(10)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0
5,58896,Analytics,region_2,Bachelor's,m,sourcing,2,31,3.0,7,0,0,85,0
6,20379,Operations,region_20,Bachelor's,f,other,1,31,3.0,5,0,0,59,0
7,16290,Operations,region_34,Master's & above,m,sourcing,1,33,3.0,6,0,0,63,0
8,73202,Analytics,region_20,Bachelor's,m,other,1,28,4.0,5,0,0,83,0
9,28911,Sales & Marketing,region_1,Master's & above,m,sourcing,1,32,5.0,5,1,0,54,0

In [15]:
df.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [16]:
df["region"].unique()

<StringArray>
[ 'region_7', 'region_22', 'region_19', 'region_23', 'region_26',  'region_2',
 'region_20', 'region_34',  'region_1',  'region_4', 'region_29', 'region_31',
 'region_15', 'region_14', 'region_11',  'region_5', 'region_28', 'region_17',
 'region_13', 'region_16', 'region_25', 'region_10', 'region_27', 'region_30',
 'region_12', 'region_21',  'region_8', 'region_32',  'region_6', 'region_33',
 'region_24',  'region_3',  'region_9', 'region_18']
Length: 34, dtype: str

In [17]:
df["region"].value_counts()

region
region_2     12343
region_22     6428
region_7      4843
region_15     2808
region_13     2648
region_26     2260
region_31     1935
region_4      1703
region_27     1659
region_16     1465
region_28     1318
region_11     1315
region_23     1175
region_29      994
region_32      945
region_19      874
region_20      850
region_14      827
region_25      819
region_17      796
region_5       766
region_6       690
region_30      657
region_8       655
region_10      648
region_1       610
region_24      508
region_12      500
region_9       420
region_21      411
region_3       346
region_34      292
region_33      269
region_18       31
Name: count, dtype: int64

In [18]:
TARGET="is_promoted"

In [19]:
cat_cols=df.select_dtypes(include="str").columns.tolist()
num_cols=df.select_dtypes(include=np.number).columns.drop(TARGET).tolist()
print("Categorical:",cat_cols)
print("Numerical:",num_cols)
#streamlit

Categorical: ['department', 'region', 'education', 'gender', 'recruitment_channel']
Numerical: ['employee_id', 'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service', 'KPIs_met >80%', 'awards_won?', 'avg_training_score']

In [20]:
for col in num_cols:
    df[col]=df[col].fillna(df[col].mean())
for col in cat_cols:
    df[col]=df[col].fillna(df[col].mode()[0])
print("missing after imputation:",df.isna().sum())

missing after imputation: employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(df["gender"])

array([0, 1, 1, ..., 1, 1, 1], shape=(54808,))

In [12]:
pd.get_dummies(
    df,
    columns=["gender"],
    dtype=int
)

,employee_id,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,gender_f,gender_m
0,65438,Sales & Marketing,region_7,Master's & above,sourcing,1,35,5.0,8,1,0,49,0,1,0
1,65141,Operations,region_22,Bachelor's,other,1,30,5.0,4,0,0,60,0,0,1
2,7513,Sales & Marketing,region_19,Bachelor's,sourcing,1,34,3.0,7,0,0,50,0,0,1
3,2542,Sales & Marketing,region_23,Bachelor's,other,2,39,1.0,10,0,0,50,0,0,1
4,48945,Technology,region_26,Bachelor's,other,1,45,3.0,2,0,0,73,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,sourcing,1,48,3.0,17,0,0,78,0,0,1
54804,74592,Operations,region_27,Master's & above,other,1,37,2.0,6,0,0,56,0,1,0
54805,13918,Analytics,region_1,Bachelor's,other,1,27,5.0,3,1,0,79,0,0,1
54806,13614,Sales & Marketing,region_9,Bachelor's,sourcing,1,29,1.0,2,0,0,45,0,0,1
54807,51526,HR,region_22,Bachelor's,other,1,27,1.0,5,0,0,49,0,0,1

In [22]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [24]:
yes_no_cols =[ 'gender']
for col in yes_no_cols:
    df[col]=df[col].map({"yes":1,"no":0})
df["gender"]=df["gender"].map({
    "gender_f":1,
    "gender_m":2,
})
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,NaN,NaN,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,NaN,NaN,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,NaN,NaN,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,NaN,NaN,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,NaN,NaN,1,45,3.0,2,0,0,73,0